<?php

include_once('ca_rooms.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_rooms_perm() {
  return array('ca_rooms change templates');
}

/**
 * Implementation of hook_menu().
 */
function ca_rooms_menu() {
  $items = array();

  $items['admin/settings/ca_rooms'] = array(
    'title' => 'Context Admin: Rooms',
    'description' => 'Change the look and feel of ca_rooms module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_rooms_admin_settings_form'),
    'access arguments' => array('ca_rooms change templates'),
    'file' => 'ca_rooms.admin.inc',
    'file path' => drupal_get_path('module', 'ca_rooms') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function ca_rooms_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_rooms_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_rooms' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_rooms') . "/css/ca_rooms.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_token_list().
 */
function ca_rooms_token_list($type = 'all') {
  $tokens = array();

  if ($type == 'node' || $type = 'all') {
    $tokens['node']['ca-rooms-parent-node-reference-path'] = t("WARNING: This token expects a particular node reference field. This should never be used outside of the ca_rooms feature.");
  }
  return $tokens;
}

/**
 * Implementation of hook_token_values().
 */
function ca_rooms_token_values($type, $object = NULL) {
  $values = array();

  switch ($type) {
    case 'node':
      $parent_node_id = $object->field_ca_rooms_rt_noderef['0']['nid'];
      $parent_node = node_load($parent_node_id);
      $parent_node_path = $parent_node->path;
      if ($parent_node_id != '') {
        $values['ca-rooms-parent-node-reference-path'] = $parent_node_path;
      }
      else {
        $values['ca-rooms-parent-node-reference-path'] = 'rooms';
      }
      break;
  }
  return $values;
}

/**
 * Implementation of hook_views_pre_build().
 */
function ca_rooms_views_pre_build(&$view) {
  if ($view->name == 'ca_rooms') {
    // Template One
    $view->display['panel_pane_4']->handler->options['title'] = variable_get('ca_rooms_views_display_title_subroom_type', 'Sub Room Types');
    $view->display['panel_pane_5']->handler->options['title'] = variable_get('ca_rooms_views_display_title_room_list', 'Rooms');
    // Template Two
    $view->display['panel_pane_9']->handler->options['title'] = variable_get('ca_rooms_views_display_title_room_list', 'Rooms');
  }
}
